### ISSUE TITLE
tar -zxf kcptun-linux-amd64-${KCP_VERSION}.tar.gz

### ISSUE THREAD

**Issue by kzhui125** [mritd/dockerfile#103]
gzip: invalid magic
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by mritd** [comment]
Please provide Dockerfile or directory name.

**Comment by kzhui125** [comment]
shadowsocks/Dockerfile

should change
ENV KCP_VERSION 20200409

**Comment by mritd** [comment]
Since the kcptun author deleted the 20200226 version of the pre-built binary file, users cannot use Dockerfile to rebuild.

Now I have upgraded the kcptun version number in the Dockerfile to the latest version and rebuilt the docker image, you can use the `latest`,` 3.3.4` or `3.3.4-20200409` tag to get the latest version of the docker image; But I cannot guarantee that the current latest version of the binary file will not be deleted by the kcptun author in the future ...

Of course, tag `3.3.4-20200228` also exists on the docker hub. This image was built before the kcptun author did not delete the pre-compiled binary file.

**Comment by kzhui125** [comment]
Thanks,
